# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Veeee

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_30069461d121401b8006d94d1246552b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c3b6d9aed4864f68ad14ba4b75e8d8e0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_30069461d121401b8006d94d1246552b }}/ghcr.io/takashikawanaka/veeee:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Veeee'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d18b142224804f8eafc5c588684f13d4 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_30069461d121401b8006d94d1246552b }}/ghcr.io/takashikawanaka/veeee:${{ github.sha }}'